In [3]:
import numpy as np
import pandas as pd
classe = pd.read_csv('notes.csv')

In [11]:
classe.head(40)

                   nom        matiere  note
0     Laurent Dagenais       Français    16
1           Guy Marois       Français    13
2      Beaufort Lesage       Français     8
3       Russell Durand       Français    10
4          Alexis Riel       Français    15
5        Leon Lapresse       Français    17
6     Orville Routhier       Français     6
7       Agramant Pepin       Français    17
8   Aiglentina Lambert       Français    16
9      Theodore Clavet       Français     8
10      Byron Lefebvre       Français    13
11        Florus Devoe       Français    10
12   Normand Arsenault       Français    17
13      Aceline Hughes       Français    12
14     Gaston Brisette       Français    19
15     Agate Grandbois       Français    12
16    Agrican Foucault       Français    10
17  Prunella Josseaume       Français    19
18      Yseult Charest       Français    11
19      Dorothee Aupry       Français    13
20       Amaury Reault       Français     8
21    Laurent Dagenais  Mathématiques     7
22          Guy Marois  Mathématiques    17
23     Beaufort Lesage  Mathématiques    15
24      Russell Durand  Mathématiques     5
25         Alexis Riel  Mathématiques     5
26       Leon Lapresse  Mathématiques     7
27    Orville Routhier  Mathématiques    12
28      Agramant Pepin  Mathématiques    18
29  Aiglentina Lambert  Mathématiques     6
30     Theodore Clavet  Mathématiques    16
31      Byron Lefebvre  Mathématiques    19
32        Florus Devoe  Mathématiques    19
33   Normand Arsenault  Mathématiques    10
34      Aceline Hughes  Mathématiques    13
35     Gaston Brisette  Mathématiques     6
36     Agate Grandbois  Mathématiques     9
37    Agrican Foucault  Mathématiques    13
38  Prunella Josseaume  Mathématiques    11
39      Yseult Charest  Mathématiques     6

In [23]:
moyenne_math = classe.groupby('matiere')['note'].mean()
moyenne_math

matiere
Biologie           10.952381
Français           12.857143
Mathématiques      11.333333
Physique/Chimie    11.523810
Name: note, dtype: float64

In [27]:
moyenne_eleve= classe.groupby('nom')['note'].mean()
moyenne_eleve

nom
Aceline Hughes        12.50
Agate Grandbois       14.25
Agramant Pepin        14.25
Agrican Foucault      11.50
Aiglentina Lambert     8.50
Alexis Riel            9.00
Amaury Reault          8.50
Beaufort Lesage       12.25
Byron Lefebvre        13.75
Dorothee Aupry        14.75
Florus Devoe          13.75
Gaston Brisette       13.50
Guy Marois            12.25
Laurent Dagenais      13.25
Leon Lapresse         12.25
Normand Arsenault     10.50
Orville Routhier       8.25
Prunella Josseaume    12.50
Russell Durand         8.50
Theodore Clavet        9.50
Yseult Charest        11.50
Name: note, dtype: float64

In [37]:
eleve_sous_moyenne = moyenne_eleve[moyenne_eleve<10]
eleve_sous_moyenne.shape[0]

6

In [41]:
classe.loc[((classe['matiere'] == 'Mathématiques') | (classe['matiere'] == 'Physique/Chimie')) & (classe['note'] >= 15), 'nom']

22         Guy Marois
23    Beaufort Lesage
28     Agramant Pepin
30    Theodore Clavet
31     Byron Lefebvre
32       Florus Devoe
65    Beaufort Lesage
68      Leon Lapresse
70     Agramant Pepin
74       Florus Devoe
78    Agate Grandbois
81     Yseult Charest
82     Dorothee Aupry
Name: nom, dtype: object